spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.port=5000
# PDF预览需要安装 LibreOffice 并设为 true
jodconverter.local.enabled=true
jodconverter.local.office-home=C:\\Program Files\\LibreOffice
